# Generated by Django 4.0.3 on 2022-03-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcation', '0002_transacao_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('C', 'Credito'), ('D', 'Debito')], max_length=1),
        ),
    ]
