# Generated by Django 4.0.3 on 2022-03-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(verbose_name='%d-%m-%Y'),
        ),
    ]
