# Generated by Django 4.0.3 on 2022-03-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='data_abertura',
            field=models.DateField(verbose_name='%d-%m-%Y'),
        ),
    ]
