# Generated by Django 4.0.3 on 2022-03-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_transacao_saldo_final_transacao_saldo_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='titular',
            field=models.CharField(max_length=46),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='status',
            field=models.CharField(max_length=13),
        ),
    ]
