# Generated by Django 4.0.3 on 2022-03-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_conta_titular_alter_transacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='titular',
            field=models.CharField(max_length=43),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='status',
            field=models.CharField(max_length=12),
        ),
    ]
