# Generated by Django 4.0.3 on 2022-03-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_conta_titular_alter_transacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='saldo_final',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='saldo_inicial',
            field=models.FloatField(blank=True),
        ),
    ]
