# Generated by Django 4.0.3 on 2022-03-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_remove_transacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='data_abertura',
            field=models.DateField(verbose_name='%m-%d-%Y'),
        ),
    ]
