# Generated by Django 4.0.3 on 2022-03-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_alter_conta_data_abertura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='saldo_final',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='saldo_inicial',
        ),
    ]
