# Generated by Django 4.0.3 on 2022-03-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_transacao_saldo_final_transacao_saldo_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='saldo_final',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='saldo_inicial',
            field=models.FloatField(blank=True),
        ),
    ]
